apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: agent-backend
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 500m 
            memory: 512Mi 
          requests:
            cpu: 100m 
            memory: 256Mi